### ISSUE TITLE
Booth 2 - API link for fetching votes of an user

### ISSUE THREAD

**Issue by cgpcsjcmp** [pablotabares/decide#111]
From an user given, we need to fetch a JSON with the votings he can vote.

**Comment by Dobloq** [comment]
The votings where an user can vote could be got searching in census' database by the user id, what will retrive the votings id where he/she is authorized to vote, and use thats ids to search in voting's database to obtain the information you need.

**Comment by pablotabares** [comment]
We are aware of that, however, our intention was for either the Census or Voting groups to develop this enhancement as it is part of your sub-systems and not ours. We could develop it ourselves but it is not the goal of this project. We do understand you may not have the time to develop it and if so we ask you to close this issue.

**Comment by camreyaro** [comment]
In Cabina subsystem we need this, too. We'd like the endpoint to receive the user token instead of the user id, if possible.

**Comment by Dobloq** [comment]
> In Cabina subsystem we need this, too. We'd like the endpoint to receive the user token instead of the user id, if possible.

What do you refer with user's token?

**Comment by camreyaro** [comment]
> What do you refer with user's token?

Every user has a token that is required in some endpoints, such as /voting POST. This token is provided after calling /authentication/login POST method.

**Comment by pablotabares** [comment]
If im not mistaken, a method which supplies the user id given his token already exists. Our idea was to concatenate those two calls otherwise you would be asking census to implement authentication procedures on their endpoint.

**Comment by camreyaro** [comment]
Didn't know that. Could you please tell me what is the endpoint for that method?

**Comment by Dobloq** [comment]
Added the API method that listen on url '/census/voter/<int:voter_id>' and return the votings in JSON format
