### ISSUE TITLE
Add vote functionality

### ISSUE THREAD

**Issue by camreyaro** [pablotabares/decide#137]
Bot must allow:
- Retrieve the list of votings in which the user can vote
- Let the user vote in every question

**Comment by awoodevpub** [comment]
tested, working properly. Clossing issue

**Comment by camreyaro** [comment]
The voting issue cannot currently be closed due to encrypting problems arising from the fact that the ElGamal implementation in Decide is non-standard, making it very difficult to adapt existing algorithms.
