### ISSUE TITLE
Control panel for mixnet

### ISSUE THREAD

**Issue by 1nt0** [pablotabares/decide#141]
A control panel in which we can view all the mixnet's authorities and their status.

**Comment by EDPVincent** [comment]
Added base files and classes to work off of (ControlPanel @ views.py, mixnet_control_panel.html)

**Comment by EDPVincent** [comment]
Added the [multiping library](https://pypi.org/project/multiping/) and a corresponding method to check the status of the saved authorities

**Comment by 1nt0** [comment]
Added Bootstrap, status icons and the names of the authorities.

**Comment by 1nt0** [comment]
Added mixnets status to fullfil the functionality of the control panel. Improved Bootstrap model too.

**Comment by EDPVincent** [comment]
Basic control panel functionality finished
