### ISSUE TITLE
Postproc - Integrate Borda prostprocesing 

### ISSUE THREAD

**Issue by AntSegJim** [pablotabares/decide#16]
Add Borda postprocessing method to tally votes

**Comment by AntSegJim** [comment]
I have already implemented this function but I need the implementation in Voting to call my function

**Comment by angelxwars** [comment]
This issue is the responsibility of booth, voting doesn't contemplate this funcionality, I'm going to add the both labbel.

**Comment by AntSegJim** [comment]
This issue will be closed as this postprocessing method will not be integrated.
