### ISSUE TITLE
CRITICAL: Failing Tests in Travis Integration

### ISSUE THREAD

**Issue by pablotabares** [pablotabares/decide#189]
There are several failing tests after the last PRs. Please, each group check their own tests and try and figure out what is going on.

https://travis-ci.org/pablotabares/decide/builds/479037987
https://travis-ci.org/pablotabares/decide/builds/479042621

**Comment by agepere** [comment]
All tests have failed for the same reason: 'Content-Type header is "text/html; charset=utf-8", not "application/json"' which is repeated in several tests. 

I think the mistake may be in auth module due to this group modifies the http request header where they can add the token or application/json

**Comment by alvarogonjim** [comment]
I don't think the problem came from the auth module, you can see in the bottom the calls returns a 404 which Content-Type header is a "text/html" not a "application/json". 
Anyways you should revert the PRs to be in a safe state.
