### ISSUE TITLE
Visualizer - Add html scripts to extract characters in dates

### ISSUE THREAD

**Issue by LuisCande** [pablotabares/decide#40]
Add html scripts to show properly the voting start date and the end date. Here we can see an example about how to fix that. (https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_substring)

**Comment by luigilgue** [comment]
I find out using the |slice option in the template is easier to do. 

**`{{ stringvar|slice:"0:3" }}`**

Please add the start and end hour too.

**Comment by LuisCande** [comment]
Finally added "|slice" option to extract characters from start and end date atributes. So now, this issue will be closed.
